// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSloNs2NMCbjdQXCYkaHPCSpdz-S4XMu8',
    appId: '1:477908814836:web:c1f95c694b004798ac07a1',
    messagingSenderId: '477908814836',
    projectId: 'teamapp-d5ab5',
    authDomain: 'teamapp-d5ab5.firebaseapp.com',
    storageBucket: 'teamapp-d5ab5.appspot.com',
    measurementId: 'G-YYTR6QZ3QC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtaIh93oTAeaah1we4cnhyFQoHQsXJKR0',
    appId: '1:477908814836:android:39a2b577aa48d8dcac07a1',
    messagingSenderId: '477908814836',
    projectId: 'teamapp-d5ab5',
    storageBucket: 'teamapp-d5ab5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCr2T5R5vZw8KDXKxJ06CEeJO51syNW1I',
    appId: '1:477908814836:ios:82d5357e409ba341ac07a1',
    messagingSenderId: '477908814836',
    projectId: 'teamapp-d5ab5',
    storageBucket: 'teamapp-d5ab5.appspot.com',
    iosClientId: '477908814836-8ehq1kip18r0p02cp7tc585c686tm758.apps.googleusercontent.com',
    iosBundleId: 'com.example.teamapp',
  );
}
